In [1]:
import numpy as np
import pandas as pd

In [2]:
labels = ['w','x','y','z']

In [7]:
list = [10,20,30,40]

In [8]:
array = np.array([10,20,30,40])

In [9]:
dict = {'w':10,'x':20,'y':30,'z':40}

In [10]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [11]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [13]:
pd.Series(list,labels)

w    10
x    20
y    30
z    40
dtype: int64

In [14]:
pd.Series(array)

0    10
1    20
2    30
3    40
dtype: int32

In [15]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

In [19]:
sports1 = pd.Series([1,2,3,4],index = ['Cricket','football','Basketball','Golf'])

In [20]:
sports1

Cricket       1
football      2
Basketball    3
Golf          4
dtype: int64

In [21]:
sports1['Cricket']

1

In [22]:
sports1[0]

1

In [25]:
sports2 = pd.Series([1,2,3,4],index = ['Cricket','football','Baseball','Golf'])

In [26]:
sports1 + sports2

Baseball      NaN
Basketball    NaN
Cricket       2.0
Golf          8.0
football      4.0
dtype: float64

In [27]:
from numpy.random import randn

In [28]:
np.random.seed(1)

In [29]:
dataframe = pd.DataFrame(randn(10,5),index='A B C D E F G H I J'.split(),
                        columns='score1 score2 score3 score4 score5'.split())

In [30]:
dataframe

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203

In [31]:
dataframe['score3']

A   -0.528172
B   -0.761207
C   -0.322417
D   -0.877858
E    0.901591
F   -0.935769
G   -0.687173
H    0.234416
I   -0.747158
J    2.100255
Name: score3, dtype: float64

In [33]:
dataframe[['score2','score1']]

     score2    score1
A -0.611756  1.624345
B  1.744812 -2.301539
C -2.060141  1.462108
D -0.172428 -1.099891
E  1.144724 -1.100619
F -0.122890 -0.683728
G -0.396754 -0.691661
H -1.117310 -0.012665
I -0.887629 -0.191836
J  0.190915 -0.636996

In [34]:
dataframe['score6'] = dataframe['score1'] + dataframe['score2']

In [35]:
dataframe

     score1    score2    score3    score4    score5    score6
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408  1.012589
B -2.301539  1.744812 -0.761207  0.319039 -0.249370 -0.556727
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769 -0.598033
D -1.099891 -0.172428 -0.877858  0.042214  0.582815 -1.272319
E -1.100619  1.144724  0.901591  0.502494  0.900856  0.044105
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355 -0.806618
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246 -1.088414
H -0.012665 -1.117310  0.234416  1.659802  0.742044 -1.129975
I -0.191836 -0.887629 -0.747158  1.692455  0.050808 -1.079465
J -0.636996  0.190915  2.100255  0.120159  0.617203 -0.446080

In [38]:
dataframe.drop('score6',axis=1,inplace=True)

In [39]:
dataframe

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203

In [40]:
dataframe.drop('A',axis=0)

     score1    score2    score3    score4    score5
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203

In [41]:
dataframe.loc['F']

score1   -0.683728
score2   -0.122890
score3   -0.935769
score4   -0.267888
score5    0.530355
Name: F, dtype: float64

In [43]:
dataframe.iloc[2]

score1    1.462108
score2   -2.060141
score3   -0.322417
score4   -0.384054
score5    1.133769
Name: C, dtype: float64

In [45]:
dataframe.loc['A','score1']

1.6243453636632417

In [46]:
dataframe.loc[['A','B'],['score1','score2']]

     score1    score2
A  1.624345 -0.611756
B -2.301539  1.744812

In [47]:
dataframe>0.5

   score1  score2  score3  score4  score5
A    True   False   False   False    True
B   False    True   False   False   False
C    True   False   False   False    True
D   False   False   False   False    True
E   False    True    True    True    True
F   False   False   False   False    True
G   False   False   False   False   False
H   False   False   False    True    True
I   False   False   False    True   False
J   False   False    True   False    True

In [48]:
dataframe[dataframe>0.5]

     score1    score2    score3    score4    score5
A  1.624345       NaN       NaN       NaN  0.865408
B       NaN  1.744812       NaN       NaN       NaN
C  1.462108       NaN       NaN       NaN  1.133769
D       NaN       NaN       NaN       NaN  0.582815
E       NaN  1.144724  0.901591  0.502494  0.900856
F       NaN       NaN       NaN       NaN  0.530355
G       NaN       NaN       NaN       NaN       NaN
H       NaN       NaN       NaN  1.659802  0.742044
I       NaN       NaN       NaN  1.692455       NaN
J       NaN       NaN  2.100255       NaN  0.617203

In [49]:
dataframe[dataframe['score1']>0.5]

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769

In [50]:
dataframe[dataframe['score1']>0.5]['score2']

A   -0.611756
C   -2.060141
Name: score2, dtype: float64

In [51]:
dataframe[(dataframe['score1']>0.5) & dataframe['score2'] > 0]

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769

In [52]:
dataframe[dataframe['score1']>0.5][0:1]

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408

In [53]:
dataframe

     score1    score2    score3    score4    score5
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
B -2.301539  1.744812 -0.761207  0.319039 -0.249370
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
D -1.099891 -0.172428 -0.877858  0.042214  0.582815
E -1.100619  1.144724  0.901591  0.502494  0.900856
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
H -0.012665 -1.117310  0.234416  1.659802  0.742044
I -0.191836 -0.887629 -0.747158  1.692455  0.050808
J -0.636996  0.190915  2.100255  0.120159  0.617203

In [55]:
dataframe.reset_index()

  index    score1    score2    score3    score4    score5
0     A  1.624345 -0.611756 -0.528172 -1.072969  0.865408
1     B -2.301539  1.744812 -0.761207  0.319039 -0.249370
2     C  1.462108 -2.060141 -0.322417 -0.384054  1.133769
3     D -1.099891 -0.172428 -0.877858  0.042214  0.582815
4     E -1.100619  1.144724  0.901591  0.502494  0.900856
5     F -0.683728 -0.122890 -0.935769 -0.267888  0.530355
6     G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
7     H -0.012665 -1.117310  0.234416  1.659802  0.742044
8     I -0.191836 -0.887629 -0.747158  1.692455  0.050808
9     J -0.636996  0.190915  2.100255  0.120159  0.617203

In [56]:
newindex = 'IND JP CAN GE IT PL FY IU RT IP'.split()

In [57]:
dataframe['countries'] = newindex

In [58]:
dataframe

     score1    score2    score3    score4    score5 countries
A  1.624345 -0.611756 -0.528172 -1.072969  0.865408       IND
B -2.301539  1.744812 -0.761207  0.319039 -0.249370        JP
C  1.462108 -2.060141 -0.322417 -0.384054  1.133769       CAN
D -1.099891 -0.172428 -0.877858  0.042214  0.582815        GE
E -1.100619  1.144724  0.901591  0.502494  0.900856        IT
F -0.683728 -0.122890 -0.935769 -0.267888  0.530355        PL
G -0.691661 -0.396754 -0.687173 -0.845206 -0.671246        FY
H -0.012665 -1.117310  0.234416  1.659802  0.742044        IU
I -0.191836 -0.887629 -0.747158  1.692455  0.050808        RT
J -0.636996  0.190915  2.100255  0.120159  0.617203        IP

In [59]:
dataframe.set_index('countries')

             score1    score2    score3    score4    score5
countries
IND        1.624345 -0.611756 -0.528172 -1.072969  0.865408
JP        -2.301539  1.744812 -0.761207  0.319039 -0.249370
CAN        1.462108 -2.060141 -0.322417 -0.384054  1.133769
GE        -1.099891 -0.172428 -0.877858  0.042214  0.582815
IT        -1.100619  1.144724  0.901591  0.502494  0.900856
PL        -0.683728 -0.122890 -0.935769 -0.267888  0.530355
FY        -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
IU        -0.012665 -1.117310  0.234416  1.659802  0.742044
RT        -0.191836 -0.887629 -0.747158  1.692455  0.050808
IP        -0.636996  0.190915  2.100255  0.120159  0.617203

In [62]:
dataframe.set_index('countries', inplace =True)

In [63]:
dataframe

             score1    score2    score3    score4    score5
countries
IND        1.624345 -0.611756 -0.528172 -1.072969  0.865408
JP        -2.301539  1.744812 -0.761207  0.319039 -0.249370
CAN        1.462108 -2.060141 -0.322417 -0.384054  1.133769
GE        -1.099891 -0.172428 -0.877858  0.042214  0.582815
IT        -1.100619  1.144724  0.901591  0.502494  0.900856
PL        -0.683728 -0.122890 -0.935769 -0.267888  0.530355
FY        -0.691661 -0.396754 -0.687173 -0.845206 -0.671246
IU        -0.012665 -1.117310  0.234416  1.659802  0.742044
RT        -0.191836 -0.887629 -0.747158  1.692455  0.050808
IP        -0.636996  0.190915  2.100255  0.120159  0.617203